name: Train Model

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: "Hugging Face dataset name"
        required: true
        default: "Add your dataset name here"
      run_name:
        description: "WandB run name"
        required: true
        default: "Add your WandB run name here"
      testing:
        description: "Testing mode"
        required: true
        default: "false"

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      DATASET_NAME: ${{ github.event.inputs.dataset }}
      WANDB_RUN_NAME: ${{ github.event.inputs.run_name }}
      TESTING: ${{ github.event.inputs.testing }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Pull latest Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/tiny-bert-trainer:latest

      - name: Run training container
        run: |
          docker run --rm \
            -e WANDB_API_KEY=$WANDB_API_KEY \
            -e TESTING=$TESTING \
            -e WANDB_RUN_NAME=$WANDB_RUN_NAME \
            -e DATASET_NAME=$DATASET_NAME \
            ${{ secrets.DOCKER_USERNAME }}/tiny-bert-trainer:latest
